// Generated by gencpp from file robobo_msgs/Blob.msg
// DO NOT EDIT!


#ifndef ROBOBO_MSGS_MESSAGE_BLOB_H
#define ROBOBO_MSGS_MESSAGE_BLOB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/String.h>
#include <std_msgs/Int32.h>
#include <opencv_apps/Point2D.h>

namespace robobo_msgs
{
template <class ContainerAllocator>
struct Blob_
{
  typedef Blob_<ContainerAllocator> Type;

  Blob_()
    : header()
    , color()
    , size()
    , center()  {
    }
  Blob_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , color(_alloc)
    , size(_alloc)
    , center(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::String_<ContainerAllocator>  _color_type;
  _color_type color;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _size_type;
  _size_type size;

   typedef  ::opencv_apps::Point2D_<ContainerAllocator>  _center_type;
  _center_type center;





  typedef boost::shared_ptr< ::robobo_msgs::Blob_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robobo_msgs::Blob_<ContainerAllocator> const> ConstPtr;

}; // struct Blob_

typedef ::robobo_msgs::Blob_<std::allocator<void> > Blob;

typedef boost::shared_ptr< ::robobo_msgs::Blob > BlobPtr;
typedef boost::shared_ptr< ::robobo_msgs::Blob const> BlobConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robobo_msgs::Blob_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robobo_msgs::Blob_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robobo_msgs::Blob_<ContainerAllocator1> & lhs, const ::robobo_msgs::Blob_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.color == rhs.color &&
    lhs.size == rhs.size &&
    lhs.center == rhs.center;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robobo_msgs::Blob_<ContainerAllocator1> & lhs, const ::robobo_msgs::Blob_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robobo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robobo_msgs::Blob_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robobo_msgs::Blob_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robobo_msgs::Blob_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robobo_msgs::Blob_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robobo_msgs::Blob_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robobo_msgs::Blob_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robobo_msgs::Blob_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fcdaa08fe5dcb5ccf3de600463bba07b";
  }

  static const char* value(const ::robobo_msgs::Blob_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfcdaa08fe5dcb5ccULL;
  static const uint64_t static_value2 = 0xf3de600463bba07bULL;
};

template<class ContainerAllocator>
struct DataType< ::robobo_msgs::Blob_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robobo_msgs/Blob";
  }

  static const char* value(const ::robobo_msgs::Blob_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robobo_msgs::Blob_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Represents a detected Color Blob\n"
"#\n"
"# Metadata about the frame\n"
"Header header\n"
"# Color of the blob\n"
"std_msgs/String color\n"
"# Size of the blob (area) in pixels\n"
"std_msgs/Int32 size\n"
"# Coordinate of the center of the blob\n"
"opencv_apps/Point2D center\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
"================================================================================\n"
"MSG: opencv_apps/Point2D\n"
"float64 x\n"
"float64 y\n"
"\n"
;
  }

  static const char* value(const ::robobo_msgs::Blob_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robobo_msgs::Blob_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.color);
      stream.next(m.size);
      stream.next(m.center);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Blob_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robobo_msgs::Blob_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robobo_msgs::Blob_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "color: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.color);
    s << indent << "size: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.size);
    s << indent << "center: ";
    s << std::endl;
    Printer< ::opencv_apps::Point2D_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOBO_MSGS_MESSAGE_BLOB_H
