// Generated by gencpp from file robobo_msgs/PlaySoundCommand.msg
// DO NOT EDIT!


#ifndef ROBOBO_MSGS_MESSAGE_PLAYSOUNDCOMMAND_H
#define ROBOBO_MSGS_MESSAGE_PLAYSOUNDCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace robobo_msgs
{
template <class ContainerAllocator>
struct PlaySoundCommand_
{
  typedef PlaySoundCommand_<ContainerAllocator> Type;

  PlaySoundCommand_()
    : sound()  {
    }
  PlaySoundCommand_(const ContainerAllocator& _alloc)
    : sound(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _sound_type;
  _sound_type sound;





  typedef boost::shared_ptr< ::robobo_msgs::PlaySoundCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robobo_msgs::PlaySoundCommand_<ContainerAllocator> const> ConstPtr;

}; // struct PlaySoundCommand_

typedef ::robobo_msgs::PlaySoundCommand_<std::allocator<void> > PlaySoundCommand;

typedef boost::shared_ptr< ::robobo_msgs::PlaySoundCommand > PlaySoundCommandPtr;
typedef boost::shared_ptr< ::robobo_msgs::PlaySoundCommand const> PlaySoundCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robobo_msgs::PlaySoundCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robobo_msgs::PlaySoundCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robobo_msgs::PlaySoundCommand_<ContainerAllocator1> & lhs, const ::robobo_msgs::PlaySoundCommand_<ContainerAllocator2> & rhs)
{
  return lhs.sound == rhs.sound;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robobo_msgs::PlaySoundCommand_<ContainerAllocator1> & lhs, const ::robobo_msgs::PlaySoundCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robobo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robobo_msgs::PlaySoundCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robobo_msgs::PlaySoundCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robobo_msgs::PlaySoundCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robobo_msgs::PlaySoundCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robobo_msgs::PlaySoundCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robobo_msgs::PlaySoundCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robobo_msgs::PlaySoundCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0935a125722801704c8ff8170000156e";
  }

  static const char* value(const ::robobo_msgs::PlaySoundCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0935a12572280170ULL;
  static const uint64_t static_value2 = 0x4c8ff8170000156eULL;
};

template<class ContainerAllocator>
struct DataType< ::robobo_msgs::PlaySoundCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robobo_msgs/PlaySoundCommand";
  }

  static const char* value(const ::robobo_msgs::PlaySoundCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robobo_msgs::PlaySoundCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Commands the robot to play a sound\n"
"#\n"
"# Plays a predefined sound. Posible \n"
"# variables: moan, purr, angry, \n"
"# approve, disapprove, discomfort, \n"
"# doubtful, laugh, likes, mumble, \n"
"# ouch, thinking, various\n"
"std_msgs/String sound\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::robobo_msgs::PlaySoundCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robobo_msgs::PlaySoundCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sound);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlaySoundCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robobo_msgs::PlaySoundCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robobo_msgs::PlaySoundCommand_<ContainerAllocator>& v)
  {
    s << indent << "sound: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.sound);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOBO_MSGS_MESSAGE_PLAYSOUNDCOMMAND_H
