// Generated by gencpp from file robobo_msgs/SetBlobCommand.msg
// DO NOT EDIT!


#ifndef ROBOBO_MSGS_MESSAGE_SETBLOBCOMMAND_H
#define ROBOBO_MSGS_MESSAGE_SETBLOBCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robobo_msgs
{
template <class ContainerAllocator>
struct SetBlobCommand_
{
  typedef SetBlobCommand_<ContainerAllocator> Type;

  SetBlobCommand_()
    : red(false)
    , green(false)
    , blue(false)
    , custom(false)  {
    }
  SetBlobCommand_(const ContainerAllocator& _alloc)
    : red(false)
    , green(false)
    , blue(false)
    , custom(false)  {
  (void)_alloc;
    }



   typedef uint8_t _red_type;
  _red_type red;

   typedef uint8_t _green_type;
  _green_type green;

   typedef uint8_t _blue_type;
  _blue_type blue;

   typedef uint8_t _custom_type;
  _custom_type custom;





  typedef boost::shared_ptr< ::robobo_msgs::SetBlobCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robobo_msgs::SetBlobCommand_<ContainerAllocator> const> ConstPtr;

}; // struct SetBlobCommand_

typedef ::robobo_msgs::SetBlobCommand_<std::allocator<void> > SetBlobCommand;

typedef boost::shared_ptr< ::robobo_msgs::SetBlobCommand > SetBlobCommandPtr;
typedef boost::shared_ptr< ::robobo_msgs::SetBlobCommand const> SetBlobCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robobo_msgs::SetBlobCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robobo_msgs::SetBlobCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robobo_msgs::SetBlobCommand_<ContainerAllocator1> & lhs, const ::robobo_msgs::SetBlobCommand_<ContainerAllocator2> & rhs)
{
  return lhs.red == rhs.red &&
    lhs.green == rhs.green &&
    lhs.blue == rhs.blue &&
    lhs.custom == rhs.custom;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robobo_msgs::SetBlobCommand_<ContainerAllocator1> & lhs, const ::robobo_msgs::SetBlobCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robobo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robobo_msgs::SetBlobCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robobo_msgs::SetBlobCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robobo_msgs::SetBlobCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robobo_msgs::SetBlobCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robobo_msgs::SetBlobCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robobo_msgs::SetBlobCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robobo_msgs::SetBlobCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96f928d9e33474244870b2bc3df1b747";
  }

  static const char* value(const ::robobo_msgs::SetBlobCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96f928d9e3347424ULL;
  static const uint64_t static_value2 = 0x4870b2bc3df1b747ULL;
};

template<class ContainerAllocator>
struct DataType< ::robobo_msgs::SetBlobCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robobo_msgs/SetBlobCommand";
  }

  static const char* value(const ::robobo_msgs::SetBlobCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robobo_msgs::SetBlobCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Commands the robot to change a the activation state of the blob detector \n"
"# for each possible color\n"
"#\n"
"\n"
"# Red blob detection\n"
"bool red\n"
"# Green blob detection\n"
"bool green\n"
"# Blue blob detection\n"
"bool blue\n"
"# Custom color detection\n"
"bool custom\n"
;
  }

  static const char* value(const ::robobo_msgs::SetBlobCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robobo_msgs::SetBlobCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.red);
      stream.next(m.green);
      stream.next(m.blue);
      stream.next(m.custom);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetBlobCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robobo_msgs::SetBlobCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robobo_msgs::SetBlobCommand_<ContainerAllocator>& v)
  {
    s << indent << "red: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.red);
    s << indent << "green: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.green);
    s << indent << "blue: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.blue);
    s << indent << "custom: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.custom);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOBO_MSGS_MESSAGE_SETBLOBCOMMAND_H
