# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robobo_msgs/SetBlobCommand.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SetBlobCommand(genpy.Message):
  _md5sum = "96f928d9e33474244870b2bc3df1b747"
  _type = "robobo_msgs/SetBlobCommand"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Commands the robot to change a the activation state of the blob detector 
# for each possible color
#

# Red blob detection
bool red
# Green blob detection
bool green
# Blue blob detection
bool blue
# Custom color detection
bool custom
"""
  __slots__ = ['red','green','blue','custom']
  _slot_types = ['bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       red,green,blue,custom

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SetBlobCommand, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.red is None:
        self.red = False
      if self.green is None:
        self.green = False
      if self.blue is None:
        self.blue = False
      if self.custom is None:
        self.custom = False
    else:
      self.red = False
      self.green = False
      self.blue = False
      self.custom = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.red, _x.green, _x.blue, _x.custom))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.red, _x.green, _x.blue, _x.custom,) = _get_struct_4B().unpack(str[start:end])
      self.red = bool(self.red)
      self.green = bool(self.green)
      self.blue = bool(self.blue)
      self.custom = bool(self.custom)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.red, _x.green, _x.blue, _x.custom))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.red, _x.green, _x.blue, _x.custom,) = _get_struct_4B().unpack(str[start:end])
      self.red = bool(self.red)
      self.green = bool(self.green)
      self.blue = bool(self.blue)
      self.custom = bool(self.custom)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
